### ISSUE TITLE
max_old_space_size too small and not configurable?

### ISSUE THREAD

**Issue by eoghanmurray** [planarnetwork/dtd2mysql#34]
@I've been getting the `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` memory error and traced it to the node max_old_space_size argument.

This appears to be set to 3000 in ./bin/dtd2mysql.sh

I tried increasing to 4096 and then finally to 16384 and that seems to have solved it.

This was from calling dtd2mysql as follows:

`$ DATABASE_USERNAME=dtd2mysql DATABASE_NAME=timetable NODE_OPTIONS='--max_old_space_size=16384' /usr/bin/ts-node ./src/index.ts --gtfs-zip ~/gtfs.zip`

However, when I run it on the system-installed version, as follows, it seems to still get the error:
`$ DATABASE_USERNAME=dtd2mysql DATABASE_NAME=timetable NODE_OPTIONS='--max_old_space_size=16384' dtd2mysql --gtfs-zip ~/gtfs.zip`

Which I presume is due to the presence of `--max_old_space_size=3000` in `/usr/bin/dtd2mysql` (just checking that now...)

**Comment by linusnorton** [comment]
Wow, that's crazy. I only end up using about 1.5GB. Can you give me the operating system, 64bit/32bit, node version and filename?

**Comment by eoghanmurray** [comment]
update: ya increasing the value that is hardcoded in `/usr/lib/node_modules/dtd2mysql/bin/dtd2mysql.sh` is able to fix it, so I imagine that indicates that you can't pass extra node options to dtd2mysql?

**Comment by eoghanmurray** [comment]
It's 64-bit on node v8.4:
```$ lscpu |grep Architecture
Architecture:          x86_64
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS```
```
$ node -v
v8.4.0
$ which node
/usr/bin/node
```

**Comment by linusnorton** [comment]
Which file are DTD/TTIS file are you using to generate the GTFS file?

**Comment by eoghanmurray** [comment]
It appears to be RJTTF921.ZIP
