### ISSUE TITLE
Filename mismatch

### ISSUE THREAD

**Issue by rml1997** [planarnetwork/dtd2mysql#50]
The filenames for the files from ATOC seem to be ignored. They are:
Timetable RJTTC345.ZIP
Routeing RJRG0281.ZIP - works
Fares RJFAC280.ZIP

Line 64 of DownloadCommands.ts seems to be the culprit:
const lastRefresh = dir.findIndex(i => i.filename.charAt(4) === "F" || i.filename.startsWith("RJRG"));

**Comment by linusnorton** [comment]
I believe the C files are incremental files. dtd2mysql will try to find the last full refresh ("F"), reset the DB tables and then apply incremental updates.

**Comment by rml1997** [comment]
Any idea how to get the last full refresh? It would be nice of them to provide that when you first sign up!

**Comment by linusnorton** [comment]
When I log into data.atoc.org I get ttis312.zip for timetables and RJFAF312.zip for fares

**Comment by linusnorton** [comment]
I'd recommend you ask about signing up for DTD

**Comment by rml1997** [comment]
I have signed up. I presume I'll get the F files when one is released or I prompt them, which I just have :)

**Comment by rml1997** [comment]
It turns out they send you only test files initially. You then need to log in via browser to confirm the test files have been received ok before they send you real files.
