### ISSUE TITLE
Replacement bus GTFS route_type

### ISSUE THREAD

**Issue by timhowgego** [planarnetwork/dtd2mysql#57]
Not critical. But, from what I can deduce, replacement bus services are being given route_type 6 when converted to GTFS. [The spec says](https://gtfs.org/reference/static/#routestxt) 6 is for suspended cable cars, while 3 is for buses. [The extended spec](https://developers.google.com/transit/gtfs/reference/extended-route-types) has a specific code for Rail Replacement Bus Service, 714, which is technically preferable here and makes it easier to filter regular from temporary bus routes within the rail data, but support for these extensions is not universal.

**Comment by linusnorton** [comment]
Seems like a conscious choice on my part:

```
      case RouteType.Gondola: return "Replacement bus";
```

I think I might use 714 instead

**Comment by linusnorton** [comment]
I've published 6.4.0 to fix this issue
