### ISSUE TITLE
Critical problem with route_type. Bus and rail trips under one route

### ISSUE THREAD

**Issue by tafflin** [planarnetwork/dtd2mysql#61]
Hi,
I found a critical problem which has an impact on companies using atoc rail data to create shapes and in some other cases.

The problem is that the same route can have trips which belong to different route_types.

I looked throught the .MCA file provided by http://data.atoc.org and I can see that the trips of train category OO/XX (route_type=2) and BR (route_type=714) are linked to the same route which has a route_type=2. I checked the data by train_uid and retail_train_id.
**The result of the issue is that in GTFS we get a mixed mode route.**

Impact: Companies using such GTFS files to generate shapes will have problems trying to generate rail shapes for bus trips. The stop locations of such replacement bus stops are far off the rail tracks

**Comment by linusnorton** [comment]
I thought the route took into account the mode, I'll check

**Comment by linusnorton** [comment]
@tafflin please try again with release 6.4.1

**Comment by tafflin** [comment]
@linusnorton hi, thanks for the quick update.
I can see that you updated the versions of dependencies. I will let you know asap if that helped

**Comment by tafflin** [comment]
@linusnorton 
I compared the new version result and the older version result and they are equal.
The bus trip with route_type=714 (according to the source .mca file) still belongs to the route_type=2 in converted GTFS.
Here is the file I tried converting: https://drive.google.com/file/d/1yIkGpbC96KGYtGFRfoi_6NdlBW8uWJ57/view?usp=sharing

**Comment by tafflin** [comment]
Hi @linusnorton ,
Did you have time to think of a possible solution? It's quite an urgent problem.
Do you need maybe additional information from my side?
I checked again on our server and there are still bus trips connected to train routes in GTFS.

**Comment by linusnorton** [comment]
I haven't had time to take a look. What TUID is causing the problem?

**Comment by tafflin** [comment]
train_uid=S12059

**Comment by linusnorton** [comment]
@tafflin this should be fixed in 6.4.2

**Comment by tafflin** [comment]
@linusnorton thank you. I can see ~500 new routes and the situation with replacement buses looks solved.
