### ISSUE TITLE
CR record in MCA file isn't handled

### ISSUE THREAD

**Issue by miklcct** [planarnetwork/dtd2mysql#85]
A CR record in an MCA file indicates a change in the service property en-route, for example, from an EMU to a DMU. It isn't currently handled in the importer.

For example, the service [L65563](https://gbtt.uk/service/L65563/2024-05-01) changes its property two times en-route, including the addition of catering at Swansea, and the power switch at Cardiff. I am looking to rewrite this timetable website using MySQL as the backend to improve performance however it isn't currently possible.

**Comment by linusnorton** [comment]
I think we'd need to add an extra table for the change records. At the moment the information just goes into the schedule table.

**Comment by miklcct** [comment]
I am seeing how I can do that, but the problem is that the `CR` record needs to reference the stop_time ID of the _next_ line in the CIF file, which isn't possible in the current parser, and for a more canonical model, the "changeable" property in the `BS` and `BX` records should also be extracted to the new table as well.

**Comment by miklcct** [comment]
The service property is a property for a section of route, so if applied "after x stop", it can be confusing.

The actual change happens when the train calls at the transition stop.
