### ISSUE TITLE
NPM version is out of date

### ISSUE THREAD

**Issue by ianbale** [planarnetwork/dtd2mysql#93]
I installed this yesterday and successfully imported some timetable data. However I am missing the change data.

I can see that this was added to the code here on github, however, it is not included in the distributed code. 

Could you update this distribution with the latest code please?

**Comment by linusnorton** [comment]
okay, that's released as 6.5.0

**Comment by ianbale** [comment]
Thanks Linus

However there seems to be a problem with that build.
On install there is no dist folder, so it doesn't run...

**Comment by linusnorton** [comment]
@ianbale could you try 6.6.1?

**Comment by ianbale** [comment]
@linusnorton Looks good now thanks
